### ISSUE TITLE
考研

### ISSUE THREAD

**Issue by liujun121533** [liujun121533/liujun121533.github.io#2]
考研记录吧

**Comment by liujun121533** [comment]
> 张宇：

-  重视基础知识的复习，重点内容，来龙去脉

- 基础计算的训练
- 数学应用的意识
- 数学考点的全面

**Comment by liujun121533** [comment]
[数学考试大纲](https://baike.baidu.com/item/%E8%80%83%E7%A0%94%E6%95%B0%E5%AD%A6%E4%B8%80%E5%A4%A7%E7%BA%B2/5124292?fr=aladdin)

**Comment by liujun121533** [comment]
> 英语近期计划：
- 对照大纲词汇表找出不熟的单词
- 05～10英语一真题
- 十年英语二真题

**Comment by liujun121533** [comment]
[考研英语大纲](https://baike.baidu.com/item/%E8%80%83%E7%A0%94%E8%8B%B1%E8%AF%AD%E5%A4%A7%E7%BA%B2/4790114?fr=aladdin)

**Comment by liujun121533** [comment]
[极限的定义](https://www.zhihu.com/question/20573378/answer/120029023?utm_source=com.youdao.note&utm_medium=social)

**Comment by liujun121533** [comment]
https://wk.baidu.com/view/dc8df7fc0342a8956bec0975f46527d3240ca6f7

**Comment by liujun121533** [comment]
https://www.zhihu.com/question/21149770/answer/111173412?utm_source=com.tencent.tim&utm_medium=social

**Comment by liujun121533** [comment]
[] 何凯文长难句
[] 1575词汇

**Comment by liujun121533** [comment]
考研是自己的选择，
而不是逃避。


一直很咸鱼🐟啊，做好规划，开始吧！

> 南邮，信号与信息处理

**Comment by SuvanCheng** [comment]
我还以为有人发了资源呢。

**Comment by liujun121533** [comment]
@SuvanCheng 上次那个六级听力的吗，感觉太慢了，就删了。百度云在这：
https://pan.baidu.com/s/1y4kzAfSf7R99JiX-eIeP0g

**Comment by liujun121533** [comment]
时间过的很快啊，现在已经是六月份了。刷了一遍李永乐的线代基础班。这个月把王式安的概率论强化班刷一遍。

**Comment by liujun121533** [comment]
时间过得太快了。前几天报名了
就快国庆了。
这段时间有些懈怠了，有时怕考不上，没什么动力。其实，考上了真的是最好的结果，但是没考上还是可以去上班，问题也不大。

**Comment by liujun121533** [comment]
这几天写完闭关修炼100题，国庆开始写数学真题。
国庆写完通原课后题，国庆后开始真题。

**Comment by liujun121533** [comment]
现在已经十一月了。过两天就要现场确认了
- 数学进度真的慢，之前的好多都忘了。慢慢捡起来吧。
- 通原状态还不错，虽然真题还是好多不会写，老是要翻书，但肯定会越来越好的😄
- 政治今天已经吧精讲精练看完了，争取这个礼拜把1000题也刷完，也就是完成第一遍。
- 英语继续刷真题吧，之前新题型看了下徐佳鹏的视频，感觉还不错。现在该慢慢开始看翻译和作文了

**Comment by liujun121533** [comment]
- 数学真的慌得不行😌
现在我想根据知识点来复习，把该拿的分拿到手，就行。
- 英语翻译的话，就是句子结构拆分和有些词的蒙猜吧。主要就是句子结构拆分，要多练练。主体前面用泛指来表示，比如有些人，这样一些机构什么的，后面再写一句，这些人，它们什么的。
- 政治的多选题真的难办啊，老是多选或者少选。目前只能拿到30分左右，分析题目前还不知道怎么搞。
- 通原最近写的几张10，11年还是比较简单的。继续加油吧✌

**Comment by liujun121533** [comment]
十二月：
只剩20天了
- 通信  只剩下18的真题没写了，现在开始要慢慢整理了，以前写的课后习题，真题，把错的，不会写的整理出来。
- 数学  不要为了写真题而写真题，现在写题就是为了看看哪里还不会-_-|| 真的要学会放弃了，把该拿的分拿了，高数各种计算，线代的方程组，二次型，概率的多维变量分布等。
看看八套卷，四套卷，还有李林，合工大的模拟卷，见识见识。
- 英语  所有的真题写完了，也应该要整理了，看看以前写错的原因，出题的套路。大小作文要开始写一写了。
- 政治  肖八模拟卷选择题写完了，慢慢再写完蒋中挺五套卷和徐涛八套卷吧。分析题的话有空读一读看一看，等肖四出来再背。
冲鸭🧐

**Comment by liujun121533** [comment]
结束了吧…

**Comment by istracker** [comment]
师兄上岸了吗

**Comment by liujun121533** [comment]
> 师兄上岸了吗

没有。。
数学考崩了，然后调回本校了

**Comment by istracker** [comment]
这个结局也不错啦 总比二战要好一些 关键是能遇到一个好的导师 希望师兄能够在本校学到自己喜欢的东西
